services:
  - type: web
    name: event-management-api
    env: node
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build && npm run db:push
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
