/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as DashboardSpeakersRouteImport } from './routes/dashboard.speakers'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as DashboardEventsIndexRouteImport } from './routes/dashboard.events.index'
import { Route as DashboardEventsNewRouteImport } from './routes/dashboard.events.new'
import { Route as DashboardEventsIdRouteImport } from './routes/dashboard.events.$id'
import { Route as DashboardEventsIdIndexRouteImport } from './routes/dashboard.events.$id.index'
import { Route as DashboardEventsIdTicketsRouteImport } from './routes/dashboard.events.$id.tickets'
import { Route as DashboardEventsIdSponsorsRouteImport } from './routes/dashboard.events.$id.sponsors'
import { Route as DashboardEventsIdSessionsRouteImport } from './routes/dashboard.events.$id.sessions'
import { Route as DashboardEventsIdEditRouteImport } from './routes/dashboard.events.$id.edit'
import { Route as DashboardEventsIdAttendeesRouteImport } from './routes/dashboard.events.$id.attendees'
import { Route as DashboardEventsIdAnalyticsRouteImport } from './routes/dashboard.events.$id.analytics'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSpeakersRoute = DashboardSpeakersRouteImport.update({
  id: '/speakers',
  path: '/speakers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEventsIndexRoute = DashboardEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEventsNewRoute = DashboardEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEventsIdRoute = DashboardEventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEventsIdIndexRoute = DashboardEventsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardEventsIdRoute,
} as any)
const DashboardEventsIdTicketsRoute =
  DashboardEventsIdTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => DashboardEventsIdRoute,
  } as any)
const DashboardEventsIdSponsorsRoute =
  DashboardEventsIdSponsorsRouteImport.update({
    id: '/sponsors',
    path: '/sponsors',
    getParentRoute: () => DashboardEventsIdRoute,
  } as any)
const DashboardEventsIdSessionsRoute =
  DashboardEventsIdSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => DashboardEventsIdRoute,
  } as any)
const DashboardEventsIdEditRoute = DashboardEventsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => DashboardEventsIdRoute,
} as any)
const DashboardEventsIdAttendeesRoute =
  DashboardEventsIdAttendeesRouteImport.update({
    id: '/attendees',
    path: '/attendees',
    getParentRoute: () => DashboardEventsIdRoute,
  } as any)
const DashboardEventsIdAnalyticsRoute =
  DashboardEventsIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => DashboardEventsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/speakers': typeof DashboardSpeakersRoute
  '/events/$slug': typeof EventsSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/events/': typeof EventsIndexRoute
  '/dashboard/events/$id': typeof DashboardEventsIdRouteWithChildren
  '/dashboard/events/new': typeof DashboardEventsNewRoute
  '/dashboard/events/': typeof DashboardEventsIndexRoute
  '/dashboard/events/$id/analytics': typeof DashboardEventsIdAnalyticsRoute
  '/dashboard/events/$id/attendees': typeof DashboardEventsIdAttendeesRoute
  '/dashboard/events/$id/edit': typeof DashboardEventsIdEditRoute
  '/dashboard/events/$id/sessions': typeof DashboardEventsIdSessionsRoute
  '/dashboard/events/$id/sponsors': typeof DashboardEventsIdSponsorsRoute
  '/dashboard/events/$id/tickets': typeof DashboardEventsIdTicketsRoute
  '/dashboard/events/$id/': typeof DashboardEventsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/speakers': typeof DashboardSpeakersRoute
  '/events/$slug': typeof EventsSlugRoute
  '/dashboard': typeof DashboardIndexRoute
  '/events': typeof EventsIndexRoute
  '/dashboard/events/new': typeof DashboardEventsNewRoute
  '/dashboard/events': typeof DashboardEventsIndexRoute
  '/dashboard/events/$id/analytics': typeof DashboardEventsIdAnalyticsRoute
  '/dashboard/events/$id/attendees': typeof DashboardEventsIdAttendeesRoute
  '/dashboard/events/$id/edit': typeof DashboardEventsIdEditRoute
  '/dashboard/events/$id/sessions': typeof DashboardEventsIdSessionsRoute
  '/dashboard/events/$id/sponsors': typeof DashboardEventsIdSponsorsRoute
  '/dashboard/events/$id/tickets': typeof DashboardEventsIdTicketsRoute
  '/dashboard/events/$id': typeof DashboardEventsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/speakers': typeof DashboardSpeakersRoute
  '/events/$slug': typeof EventsSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/events/': typeof EventsIndexRoute
  '/dashboard/events/$id': typeof DashboardEventsIdRouteWithChildren
  '/dashboard/events/new': typeof DashboardEventsNewRoute
  '/dashboard/events/': typeof DashboardEventsIndexRoute
  '/dashboard/events/$id/analytics': typeof DashboardEventsIdAnalyticsRoute
  '/dashboard/events/$id/attendees': typeof DashboardEventsIdAttendeesRoute
  '/dashboard/events/$id/edit': typeof DashboardEventsIdEditRoute
  '/dashboard/events/$id/sessions': typeof DashboardEventsIdSessionsRoute
  '/dashboard/events/$id/sponsors': typeof DashboardEventsIdSponsorsRoute
  '/dashboard/events/$id/tickets': typeof DashboardEventsIdTicketsRoute
  '/dashboard/events/$id/': typeof DashboardEventsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/analytics'
    | '/dashboard/notifications'
    | '/dashboard/speakers'
    | '/events/$slug'
    | '/dashboard/'
    | '/events/'
    | '/dashboard/events/$id'
    | '/dashboard/events/new'
    | '/dashboard/events/'
    | '/dashboard/events/$id/analytics'
    | '/dashboard/events/$id/attendees'
    | '/dashboard/events/$id/edit'
    | '/dashboard/events/$id/sessions'
    | '/dashboard/events/$id/sponsors'
    | '/dashboard/events/$id/tickets'
    | '/dashboard/events/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard/analytics'
    | '/dashboard/notifications'
    | '/dashboard/speakers'
    | '/events/$slug'
    | '/dashboard'
    | '/events'
    | '/dashboard/events/new'
    | '/dashboard/events'
    | '/dashboard/events/$id/analytics'
    | '/dashboard/events/$id/attendees'
    | '/dashboard/events/$id/edit'
    | '/dashboard/events/$id/sessions'
    | '/dashboard/events/$id/sponsors'
    | '/dashboard/events/$id/tickets'
    | '/dashboard/events/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/analytics'
    | '/dashboard/notifications'
    | '/dashboard/speakers'
    | '/events/$slug'
    | '/dashboard/'
    | '/events/'
    | '/dashboard/events/$id'
    | '/dashboard/events/new'
    | '/dashboard/events/'
    | '/dashboard/events/$id/analytics'
    | '/dashboard/events/$id/attendees'
    | '/dashboard/events/$id/edit'
    | '/dashboard/events/$id/sessions'
    | '/dashboard/events/$id/sponsors'
    | '/dashboard/events/$id/tickets'
    | '/dashboard/events/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  EventsSlugRoute: typeof EventsSlugRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/speakers': {
      id: '/dashboard/speakers'
      path: '/speakers'
      fullPath: '/dashboard/speakers'
      preLoaderRoute: typeof DashboardSpeakersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/events/': {
      id: '/dashboard/events/'
      path: '/events'
      fullPath: '/dashboard/events/'
      preLoaderRoute: typeof DashboardEventsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/events/new': {
      id: '/dashboard/events/new'
      path: '/events/new'
      fullPath: '/dashboard/events/new'
      preLoaderRoute: typeof DashboardEventsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/events/$id': {
      id: '/dashboard/events/$id'
      path: '/events/$id'
      fullPath: '/dashboard/events/$id'
      preLoaderRoute: typeof DashboardEventsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/events/$id/': {
      id: '/dashboard/events/$id/'
      path: '/'
      fullPath: '/dashboard/events/$id/'
      preLoaderRoute: typeof DashboardEventsIdIndexRouteImport
      parentRoute: typeof DashboardEventsIdRoute
    }
    '/dashboard/events/$id/tickets': {
      id: '/dashboard/events/$id/tickets'
      path: '/tickets'
      fullPath: '/dashboard/events/$id/tickets'
      preLoaderRoute: typeof DashboardEventsIdTicketsRouteImport
      parentRoute: typeof DashboardEventsIdRoute
    }
    '/dashboard/events/$id/sponsors': {
      id: '/dashboard/events/$id/sponsors'
      path: '/sponsors'
      fullPath: '/dashboard/events/$id/sponsors'
      preLoaderRoute: typeof DashboardEventsIdSponsorsRouteImport
      parentRoute: typeof DashboardEventsIdRoute
    }
    '/dashboard/events/$id/sessions': {
      id: '/dashboard/events/$id/sessions'
      path: '/sessions'
      fullPath: '/dashboard/events/$id/sessions'
      preLoaderRoute: typeof DashboardEventsIdSessionsRouteImport
      parentRoute: typeof DashboardEventsIdRoute
    }
    '/dashboard/events/$id/edit': {
      id: '/dashboard/events/$id/edit'
      path: '/edit'
      fullPath: '/dashboard/events/$id/edit'
      preLoaderRoute: typeof DashboardEventsIdEditRouteImport
      parentRoute: typeof DashboardEventsIdRoute
    }
    '/dashboard/events/$id/attendees': {
      id: '/dashboard/events/$id/attendees'
      path: '/attendees'
      fullPath: '/dashboard/events/$id/attendees'
      preLoaderRoute: typeof DashboardEventsIdAttendeesRouteImport
      parentRoute: typeof DashboardEventsIdRoute
    }
    '/dashboard/events/$id/analytics': {
      id: '/dashboard/events/$id/analytics'
      path: '/analytics'
      fullPath: '/dashboard/events/$id/analytics'
      preLoaderRoute: typeof DashboardEventsIdAnalyticsRouteImport
      parentRoute: typeof DashboardEventsIdRoute
    }
  }
}

interface DashboardEventsIdRouteChildren {
  DashboardEventsIdAnalyticsRoute: typeof DashboardEventsIdAnalyticsRoute
  DashboardEventsIdAttendeesRoute: typeof DashboardEventsIdAttendeesRoute
  DashboardEventsIdEditRoute: typeof DashboardEventsIdEditRoute
  DashboardEventsIdSessionsRoute: typeof DashboardEventsIdSessionsRoute
  DashboardEventsIdSponsorsRoute: typeof DashboardEventsIdSponsorsRoute
  DashboardEventsIdTicketsRoute: typeof DashboardEventsIdTicketsRoute
  DashboardEventsIdIndexRoute: typeof DashboardEventsIdIndexRoute
}

const DashboardEventsIdRouteChildren: DashboardEventsIdRouteChildren = {
  DashboardEventsIdAnalyticsRoute: DashboardEventsIdAnalyticsRoute,
  DashboardEventsIdAttendeesRoute: DashboardEventsIdAttendeesRoute,
  DashboardEventsIdEditRoute: DashboardEventsIdEditRoute,
  DashboardEventsIdSessionsRoute: DashboardEventsIdSessionsRoute,
  DashboardEventsIdSponsorsRoute: DashboardEventsIdSponsorsRoute,
  DashboardEventsIdTicketsRoute: DashboardEventsIdTicketsRoute,
  DashboardEventsIdIndexRoute: DashboardEventsIdIndexRoute,
}

const DashboardEventsIdRouteWithChildren =
  DashboardEventsIdRoute._addFileChildren(DashboardEventsIdRouteChildren)

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardSpeakersRoute: typeof DashboardSpeakersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardEventsIdRoute: typeof DashboardEventsIdRouteWithChildren
  DashboardEventsNewRoute: typeof DashboardEventsNewRoute
  DashboardEventsIndexRoute: typeof DashboardEventsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardSpeakersRoute: DashboardSpeakersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardEventsIdRoute: DashboardEventsIdRouteWithChildren,
  DashboardEventsNewRoute: DashboardEventsNewRoute,
  DashboardEventsIndexRoute: DashboardEventsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  EventsSlugRoute: EventsSlugRoute,
  EventsIndexRoute: EventsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
